
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "ext/src",
  "Taxidermy": "app",
  "Framework": "framework",
  "Ext.ux.GroupTreeChunker": "ext/src/ux/GroupTabPanel.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Taxidermy.view.MainTabContainer": [],
  "Framework.ux.UxDependencies": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Taxidermy.view.catalog.specie.SelectSpecie": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Taxidermy.view.Main": [],
  "Taxidermy.controller.catalog.specie.SelectSpecieController": [],
  "Framework.util.MD5Util": [],
  "Framework.ux.container.TabContainer": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Framework.ux.view.CardViewsContainer": [],
  "Framework.util.ObjectUtil": [],
  "Ext.ux.CheckColumn": [],
  "Taxidermy.defaults.Constants": [],
  "Ext.ux.PreviewPlugin": [],
  "Taxidermy.ux.ImageView": [],
  "Framework.ux.data.RestProxy": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Framework.ux.data.RestJsonReader": [],
  "Ext.ux.event.Recorder": [],
  "Framework.ux.util.EnhancedComponentDragger": [],
  "Taxidermy.controller.MainController": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.TabScrollerMenu": [],
  "Taxidermy.view.Header": [],
  "Ext.ux.IFrame": [],
  "Taxidermy.store.SpecieItems": [],
  "Taxidermy.controller.catalog.habitat.SelectHabitatController": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "Framework.core.ViewsManager": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Framework.core.LocalizationManager": [],
  "Ext.ux.FieldReplicator": [],
  "Taxidermy.store.MountItems": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Framework.util.HotkeysUtil": [],
  "Framework.core.ErrorsManager": [],
  "Framework.util.FileLoader": [],
  "Taxidermy.controller.Main": [],
  "Framework.core.Defaults": [],
  "Framework.core.CoreDependencies": [],
  "Taxidermy.view.catalog.habitat.SelectHabitat": [],
  "Ext.ux.GMapPanel": [],
  "Framework.core.EventBus": [],
  "Framework.ux.view.TabViewsContainer": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Taxidermy.model.ImageItem": [],
  "Ext.ux.GroupTreeChunker": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Framework.core.FrameworkEvents": [],
  "Ext.ux.layout.Center": [],
  "Taxidermy.view.catalog.mount.SelectMount": [],
  "Ext.ux.DataView.Animated": [],
  "Taxidermy.ux.PreviewImageDisplay": [],
  "Framework.util.DragSelectionUtil": [],
  "Framework.ux.popup.ErrorWindow": [],
  "Taxidermy.controller.catalog.mount.SelectMountController": [],
  "Taxidermy.store.HabitatItems": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Framework.ux.view.BaseViewsContainer": [],
  "Framework.core.ViewItem": [],
  "Framework.Main": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Framework.core.ModelLocator": [],
  "Framework.util.MultipleScriptInjector": [],
  "Ext.ux.event.Player": [],
  "Framework.util.UtilDependencies": [],
  "Framework.ux.view.SimpleViewsContainer": [],
  "Taxidermy.util.TaxidermyUrlUtil": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Taxidermy.view.Viewport": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "Framework.core.SecurityManager": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Taxidermy.ux.TaxidermyUxDependencies": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Framework.util.StylesUtil": [],
  "Ext.ux.grid.FiltersFeature": []
});
Ext.ClassManager.addNameAliasMappings({
  "Taxidermy.view.MainTabContainer": [
    "widget.maintabcontainer"
  ],
  "Framework.ux.UxDependencies": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Taxidermy.view.catalog.specie.SelectSpecie": [
    "widget.selectspecie"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Taxidermy.view.Main": [
    "widget.main"
  ],
  "Taxidermy.controller.catalog.specie.SelectSpecieController": [],
  "Framework.util.MD5Util": [],
  "Framework.ux.container.TabContainer": [
    "widget.tabcontainer"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Framework.ux.view.CardViewsContainer": [
    "widget.cardviewscontainer"
  ],
  "Framework.util.ObjectUtil": [],
  "Ext.ux.CheckColumn": [
    "widget.checkcolumn"
  ],
  "Taxidermy.defaults.Constants": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Taxidermy.ux.ImageView": [
    "widget.imageview"
  ],
  "Framework.ux.data.RestProxy": [
    "proxy.restproxy"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Framework.ux.data.RestJsonReader": [
    "reader.restjsonreader"
  ],
  "Ext.ux.event.Recorder": [],
  "Framework.ux.util.EnhancedComponentDragger": [
    "widget.enhancedcomponentdragger"
  ],
  "Taxidermy.controller.MainController": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Taxidermy.view.Header": [
    "widget.taxidermyheader"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Taxidermy.store.SpecieItems": [],
  "Taxidermy.controller.catalog.habitat.SelectHabitatController": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Framework.core.ViewsManager": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Framework.core.LocalizationManager": [],
  "Ext.ux.FieldReplicator": [],
  "Taxidermy.store.MountItems": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Framework.util.HotkeysUtil": [],
  "Framework.core.ErrorsManager": [],
  "Framework.util.FileLoader": [],
  "Taxidermy.controller.Main": [],
  "Framework.core.Defaults": [],
  "Framework.core.CoreDependencies": [],
  "Taxidermy.view.catalog.habitat.SelectHabitat": [
    "widget.selecthabitat"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Framework.core.EventBus": [],
  "Framework.ux.view.TabViewsContainer": [
    "widget.tabviewscontainer"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Taxidermy.model.ImageItem": [],
  "Ext.ux.GroupTreeChunker": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Framework.core.FrameworkEvents": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Taxidermy.view.catalog.mount.SelectMount": [
    "widget.selectmount"
  ],
  "Ext.ux.DataView.Animated": [],
  "Taxidermy.ux.PreviewImageDisplay": [
    "widget.previewimagedisplay"
  ],
  "Framework.util.DragSelectionUtil": [],
  "Framework.ux.popup.ErrorWindow": [
    "widget.errorwindow"
  ],
  "Taxidermy.controller.catalog.mount.SelectMountController": [],
  "Taxidermy.store.HabitatItems": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Framework.ux.view.BaseViewsContainer": [
    "widget.baseviewscontainer"
  ],
  "Framework.core.ViewItem": [],
  "Framework.Main": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [
    "plugin.rowexpander"
  ],
  "Framework.core.ModelLocator": [],
  "Framework.util.MultipleScriptInjector": [],
  "Ext.ux.event.Player": [],
  "Framework.util.UtilDependencies": [],
  "Framework.ux.view.SimpleViewsContainer": [
    "widget.simpleviewscontainer"
  ],
  "Taxidermy.util.TaxidermyUrlUtil": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Taxidermy.view.Viewport": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Framework.core.SecurityManager": [],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Taxidermy.ux.TaxidermyUxDependencies": [],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Framework.util.StylesUtil": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ]
});
