Ext.define('Taxidermy.defaults.Constants',{

    statics: {
        ITEM_NOT_FOUND_INDEX: -1,
        TAXIDERMY_OPTION_TYPE_SPECIE: "SPECIE",
        TAXIDERMY_OPTION_TYPE_MOUNT: "MOUNT",
        TAXIDERMY_OPTION_TYPE_POSE: "POSE",
        TAXIDERMY_OPTION_TYPE_BASE: "BASE",
        TAXIDERMY_OPTION_TYPE_HABITAT: "HABITAT",
        IMAGE_VIEW_SELECTION_MODE_SINGLE: "SINGLE",
        IMAGE_VIEW_SELECTION_MODE_SIMPLE: "SIMPLE",
        IMAGE_VIEW_SELECTION_MODE_MULTIPLE: "MULTI"
    }

});